### ISSUE TITLE
ArborX fails to compile with CUDA 11.0.3-11.3.3

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#849]
Compiling `benchmarks/dbscan` results in 
```
nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)
nvcc error   : 'cicc' core dumped
make[2]: *** [benchmarks/dbscan/CMakeFiles/ArborX_Benchmark_DBSCAN.exe.dir/build.make:76: benchmarks/dbscan/CMakeFiles/ArborX_Benchmark_DBSCAN.exe.dir/dbscan_3.cpp.o] Error 139
```

Compiling `examples/dbscan` results in
```
<snip>/arborx/src/ArborX_DBSCAN.hpp: In instantiation of 'Kokkos::View<int*, typename ArborX::AccessTraits<Primitives, ArborX::PrimitivesTag, void>::memory_space> ArborX::dbscan(const ExecutionSpace&, const Primitives&, float, int, const ArborX::DBSCAN::Parameters&) [with ExecutionSpace = Kokkos::Cuda; Primitives = Kokkos::View<ArborX::Point*, Kokkos::CudaSpace>; typename ArborX::AccessTraits<Primitives, ArborX::PrimitivesTag>::memory_space = Kokkos::CudaSpace]':
<snip>/arborx/examples/dbscan/example_dbscan.cpp:59:64:   required from here
<snip>/arborx/src/ArborX_DBSCAN.hpp:301:14: error: 'HalfTraversal' was not declared in this scope; did you mean 'ArborX::Details::HalfTraversal'?
  301 |       Details::HalfTraversal(
      |       ~~~~~~~^~~~~~~~~~~~~~~~
      | ArborX::Details::HalfTraversal
<snip>/arborx/src/details/ArborX_DetailsHalfTraversal.hpp:24:8: note: 'ArborX::Details::HalfTraversal' declared here
   24 | struct HalfTraversal
      |        ^~~~~~~~~~~~~
<snip>/arborx/src/ArborX_DBSCAN.hpp:323:14: error: 'HalfTraversal' was not declared in this scope; did you mean 'ArborX::Details::HalfTraversal'?
  323 |       Details::HalfTraversal(exec_space, bvh,
      |       ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                   
      | ArborX::Details::HalfTraversal
<snip>/arborx/src/details/ArborX_DetailsHalfTraversal.hpp:24:8: note: 'ArborX::Details::HalfTraversal' declared here
   24 | struct HalfTraversal
      |        ^~~~~~~~~~~~~
nvcc_internal_extended_lambda_implementation:991:13: error: 'static decltype (typename __nv_hdl_helper_trait_outer<IsMutable, HasFuncPtrConv, CaptureArgs ...>::__nv_hdl_helper_trait<Tag, Lambda>::get(lam, __nv_hdl_create_wrapper_t::__nv_hdl_create_wrapper::args ...)) __nv_hdl_create_wrapper_t<IsMutable, HasFuncPtrConv, Tag, CaptureArgs>::__nv_hdl_create_wrapper(Lambda&&, CaptureArgs ...) [with Lambda = ArborX::dbscan(const ExecutionSpace&, const Primitives&, float, int, const ArborX::DBSCAN::Parameters&) [with ExecutionSpace = Kokkos::Cuda; Primitives = Kokkos::View<ArborX::Point*, Kokkos::CudaSpace>; typename ArborX::AccessTraits<Primitives, ArborX::PrimitivesTag>::memory_space = Kokkos::CudaSpace]::<lambda(int)>; bool IsMutable = false; bool HasFuncPtrConv = false; Tag = __nv_dl_tag<Kokkos::View<int*, Kokkos::CudaSpace> (*)(const Kokkos::Cuda&, const Kokkos::View<ArborX::Point*, Kokkos::CudaSpace>&, float, int, const ArborX::DBSCAN::Parameters&), ArborX::dbscan<Kokkos::Cuda, Kokkos::View<ArborX::Point*, Kokkos::CudaSpace> >, 1>; CaptureArgs = {Kokkos::View<int*, Kokkos::CudaSpace>, Kokkos::View<unsigned int*, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> >}; decltype (typename __nv_hdl_helper_trait_outer<IsMutable, HasFuncPtrConv, CaptureArgs ...>::__nv_hdl_helper_trait<Tag, Lambda>::get(lam, __nv_hdl_create_wrapper_t::__nv_hdl_create_wrapper::args ...)) = __nv_hdl_wrapper_t<false, false, __nv_dl_tag<Kokkos::View<int*, Kokkos::CudaSpace> (*)(const Kokkos::Cuda&, const Kokkos::View<ArborX::Point*, Kokkos::CudaSpace>&, float, int, const ArborX::DBSCAN::Parameters&), ArborX::dbscan<Kokkos::Cuda, Kokkos::View<ArborX::Point*, Kokkos::CudaSpace> >, 1>, void(int), Kokkos::View<int*, Kokkos::CudaSpace>, Kokkos::View<unsigned int*, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> > >; typename __nv_hdl_helper_trait_outer<IsMutable, HasFuncPtrConv, CaptureArgs ...>::__nv_hdl_helper_trait<Tag, Lambda> = __nv_hdl_helper_trait_outer<false, false, Kokkos::View<int*, Kokkos::CudaSpace>, Kokkos::View<unsigned int*, Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace> > >::__nv_hdl_helper_trait<__nv_dl_tag<Kokkos::View<int*, Kokkos::CudaSpace> (*)(const Kokkos::Cuda&, const Kokkos::View<ArborX::Point*, Kokkos::CudaSpace>&, float, int, const ArborX::DBSCAN::Parameters&), ArborX::dbscan<Kokkos::Cuda, Kokkos::View<ArborX::Point*, Kokkos::CudaSpace> >, 1>, ArborX::dbscan(const ExecutionSpace&, const Primitives&, float, int, const ArborX::DBSCAN::Parameters&) [with ExecutionSpace = Kokkos::Cuda; Primitives = Kokkos::View<ArborX::Point*, Kokkos::CudaSpace>; typename ArborX::AccessTraits<Primitives, ArborX::PrimitivesTag>::memory_space = Kokkos::CudaSpace]::<lambda(int)> >]', declared using local type 'ArborX::dbscan(const ExecutionSpace&, const Primitives&, float, int, const ArborX::DBSCAN::Parameters&) [with ExecutionSpace = Kokkos::Cuda; Primitives = Kokkos::View<ArborX::Point*, Kokkos::CudaSpace>; typename ArborX::AccessTraits<Primitives, ArborX::PrimitivesTag>::memory_space = Kokkos::CudaSpace]::<lambda(int)>', is used but never defined [-fpermissive]
```
